### ISSUE TITLE
Centering Framework Logo in ZBminimal

### ISSUE THREAD

**Issue by NL-TCH** [martiandeath/Framework-Backgrounds#2]
Hey @martiandeath ,
Can i request a change to one of the pictures (as i am no expert at this)
can you center the framework logo in [FrameworkZBminimal](https://github.com/martiandeath/Framework-Backgrounds/blob/main/FrameworkZBMininal.jpg)?
I would really appreciate it!
![afbeelding](https://user-images.githubusercontent.com/58732773/147515874-c7051a7a-5fc2-45e2-b453-8da4bbb16302.png)

**Comment by martiandeath** [comment]
I didn’t actually make this one, so I can’t really help with that, you can probably find the image on the framework forums and ask them through there

**Comment by NL-TCH** [comment]
ah oke thanks 👍🏼
